### ISSUE TITLE
Feature request: live demo

### ISSUE THREAD

**Issue by juliaogris** [anz-bank/anz-codebreakers#1]
Would be lovely to have a (link to a) live demo!

**Comment by loliver** [comment]
I actually put the link on the GitHub description, it's just up on GitHub Pages :)

https://anz-bank.github.io/anz-codebreakers/

**Comment by juliaogris** [comment]
oups! apologies! great.

**Comment by loliver** [comment]
I have a feeling I actually added it after you posted the issue, was doing bits and pieces until about 11.30 last night, haha.
